name: tom_analyzer
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  args: ^2.4.0
  collection: ^1.18.0
  crypto: ^3.0.3
  path: ^1.9.0
  yaml: ^3.1.2
  build: ^4.0.4
  tom_analyzer_model:
    path: ../tom_analyzer_model
  tom_build_base:
    path: ../../tom_module_basics/tom_build_base
  tom_d4rt_ast:
    path: ../tom_d4rt_ast

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^6.0.0
  mocktail: ^1.0.3
  test: ^1.25.6
