name: tom_reflection_generator
description: Standalone reflection generator (builder + CLI) for the Tom framework.
version: 1.0.2
repository: https://github.com/al-the-bear/tom_reflection

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  build: ^4.0.3
  dart_style: ^3.0.0
  glob: ^2.1.2
  logging: ^1.3.0
  path: ^1.9.0
  pub_semver: ^2.2.0
  tom_reflection: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
