name: tom_reflection
description: >
  Runtime reflection support based on code generation, using 'capabilities' to
  specify which operations to support. This is a fork of the 'reflectable' package
  with modifications to better suit the Tom framework's needs and some bug fixes.
version: 1.0.2
repository: https://github.com/al-the-bear/tom_reflection

environment:
  sdk: ^3.9.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^5.0.0
  test: ^1.25.0
  tom_reflection_generator:
    path: ../tom_reflection_generator
